-- 코드를 입력하세요
SELECT MEMBER_ID,MEMBER_NAME,GENDER,DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE DATE_FORMAT(DATE_OF_BIRTH, '%m-%d')>='03-01' 
AND  DATE_FORMAT(DATE_OF_BIRTH, '%m-%d')<'04-01'
AND TLNO is not null
AND GENDER = 'W'
order by MEMBER_ID asc;
 